# Generated by Django 4.1 on 2024-04-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_add_categories_frequencies_advisors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Financial Advisor', 'verbose_name_plural': 'Financial Advisors'},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['start_date'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterModelOptions(
            name='budgetcategory',
            options={'ordering': ['category__expense_category_name'], 'verbose_name': 'Budget Category', 'verbose_name_plural': 'Budget Categories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['date'], 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='client',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='budget.advisor'),
        ),
    ]
